Aplicacao/Models/ErrorViewModel.cs
using System;

namespace Aplicacao.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Aplicacao/Controllers/HomeController.cs
using Aplicacao.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Aplicacao.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Aplicacao/Controllers/PessoaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aplicacao.Controllers
{
    public class PessoaController : Controller
    {
        public IActionResult Cadastro()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Adicionar()
        {
            return View();
        }

        public IActionResult GetPessoa(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        public IActionResult ListarTodas()
        {
            return View();
        }
    }
}

Aplicacao/Views/Home/Index.cshtml
@{ 
    ViewData["Title"] = "Home Page"; 
}

@section Scripts {
    <script src="~/js/Home.js"></script>
}

<div class="text-center">
    <h1 class="display-4">Bem vindo ao sistema de gestão de contatos</h1>
    <p>Faça login ou cadastre-se.</p>
</div>

Aplicacao/Views/Pessoa/Adicionar.cshtml
@{ ViewData["Title"] = "Adicionar Pessoa"; }

@section Styles {
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.min.css">
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery.timepicker.min.css">
}

@section Scripts {
    <script src="~/js/PessoaAdicionar.js"></script>
    <script src="~/lib/jquery-mask/jquery-mask.min.js"></script>
}

<h1>Adicionar Pessoa</h1>

<form id="form-adicionar">
    <div class="row">
        <div class="col-md-6">
            <div id="form-telefone">
                <div class="form-group">
                    <label for="nome">Nome</label>
                    <input type="text" class="form-control" id="nome">
                </div>
                <div class="form-group">
                    <label for="dataNascimento">Data de Nascimento</label>
                    <input type="text" class="form-control" id="dataNascimento" placeholder="Ex: 19/06/1984">
                </div>
                <div class="form-group">
                    <label for="telefone1">Telefone 1</label>
                    <input type="text" class="form-control" id="telefone1">
                </div>
            </div>
            
           

            <button type="button" class="btn btn-sm btn-info" id="adicionarTelefone" onclick="AdicionarTelefone()"> + Adicionar Telefone</button>
            <br /><br />
            <button class="btn btn-primary" id="salvar">Salvar</button>
        </div>
    </div>
</form>

Aplicacao/Views/Pessoa/Cadastro.cshtml
@{ ViewData["Title"] = "Cadastro"; }

@section Scripts {
    <script src="~/js/PessoaCadastro.js"></script>
}

<h1>Cadastro</h1>

<form id="form-cadastro">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="nome">Nome</label>
                <input type="text" class="form-control" name="nome">
            </div>
            <div class="form-group">
                <label for="email">E-mail</label>
                <input type="email" class="form-control" name="email">
            </div>
            <div class="form-group">
                <label for="senha">Senha</label>
                <input type="password" class="form-control" name="senha" id="senha">
            </div>
            <div class="form-group">
                <label for="confirmarSenha">Repetir Senha</label>
                <input type="password" class="form-control" id="confirmarSenha">
            </div>
            <button class="btn btn-primary" id="cadastrar">Cadastrar</button>
        </div>
    </div>
</form>

Aplicacao/Views/Pessoa/GetPessoa.cshtml
@{ ViewData["Title"] = "Alterar Pessoa"; }

@section Styles {
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.min.css">
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery.timepicker.min.css">
}

@section Scripts {
    <script>
        var id = @(ViewBag.Id);
    </script>
    <script src="~/js/PessoaExpandir.js"></script>
    <script src="~/lib/jquery-mask/jquery-mask.min.js"></script>
}

<h1>Detalhes da Pessoa</h1>

<div class="row">
    <div class="col-md-6">
        <div id="form-telefone">
            <div class="form-group">
                <label for="nome">Nome</label>
                <input type="text" class="form-control" id="nome" disabled>
            </div>
            <div class="form-group">
                <label for="dataNascimento">Data de Nascimento</label>
                <input type="text" class="form-control" id="dataNascimento" disabled>
            </div>
               
        </div>      
    </div>
</div>

Aplicacao/Views/Pessoa/ListarTodas.cshtml
@{ 
    ViewData["Title"] = "Pessoas Cadastradas"; 
}

@section Styles {
    <link rel="stylesheet" href="~/lib/dataTables/dataTables.bootstrap4.min.css">
}

@section Scripts {
    <script src="~/lib/dataTables/jquery.dataTables.min.js"></script>
    <script src="~/lib/dataTables/dataTables.bootstrap4.min.js"></script>
    <script src="~/js/PessoaListarTodas.js"></script>
}

<h1>
    Pessoas Cadastradas
    <span id="btnMais" style="margin-left:400px">
        <button type="button" class="btn btn-primary" onclick="buscar()">Apenas com mais de 1 telefone</button>
    </span>
    <span id="btnTodas" style="margin-left:400px;display: none;">
        <button type="button" class="btn btn-info" onclick="buscar()">Listar Todas</button>
    </span>
</h1>

<div style="margin-top:30px" id="resultado">
  
</div>

Aplicacao/Views/Pessoa/Login.cshtml
@{ 
    ViewData["Title"] = "Login"; 
}

@section Scripts {
    <script src="~/js/PessoaLogin.js"></script>
}

<h1>Login</h1>

<form id="form-login">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="email">E-mail</label>
                <input type="email" class="form-control" name="email">
            </div>
            <div class="form-group">
                <label for="senha">Senha</label>
                <input type="password" class="form-control" name="senha">
            </div>
            <button class="btn btn-primary" id="login">Entrar</button>
        </div>
    </div>
</form>

Aplicacao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestor de Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3 bg-dark">
            <div class="container">
                <span class="navbar-brand" asp-area="">Gestor de Contatos</span>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 menuLogado">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Pessoa" asp-action="ListarTodas">Pessoas Cadastradas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Pessoa" asp-action="Adicionar">Adicionar Pessoa</a>
                        </li>                        
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse order-3">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item menuNaoLogado" style="display:none">
                            <a class="nav-link" asp-area="" asp-controller="Pessoa" asp-action="Cadastro">Cadastrar-se</a>
                        </li>
                        <li class="nav-item menuNaoLogado" style="display:none">
                            <a class="nav-link" asp-area="" asp-controller="Pessoa" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item menuLogado">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index" id="logoff">Logoff</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-serializejson/jquery.serializejson.js"></script>
    <script src="~/lib/emodal/dist/eModal.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Menu.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>